services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  B13\Sessionpassword\:
    resource: '../Classes/*'

  B13\Sessionpassword\EventListener\ModifyResolvedFrontendGroups:
    tags:
      - name: event.listener
        identifier: 'txSessionPasswordGroups'
        event: TYPO3\CMS\Frontend\Authentication\ModifyResolvedFrontendGroupsEvent
