services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  B13\Sessionpassword\EventListener\ModifyResolvedFrontendGroups:
    tags:
      - name: event.listener
        identifier: 'sessionPasswordGroups'
        event: TYPO3\CMS\Frontend\Authentication\ModifyResolvedFrontendGroupsEvent
